<a href="https://colab.research.google.com/github/ayakawamura/practice_python/blob/main/numpy_editor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy exercises


1. データの状態を確認する方法について学習します。（4問）
2. 配列について学習します。（4問）
3. スライスについて学習します。（5問）
4. 行列について学習します。（基礎）（6問）
5. 行列について学習します。（応用）（7問）
6. numpyでよく使う機能について学習します。（14問）

### 0. 事前準備

#### 0.1 「numpyを読み込んでください。」

In [ ]:
import numpy as np

#### 0.2 「以下のコードを読み込んでください。」

In [ ]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### 1. データの状態を確認する方法について学習します。（4問）

#### 1.1 「行列の大きさを確認してください。」

In [ ]:
a.shape

(3, 5)

#### 1.2 「行列の軸数（次元）を確認してください。」

In [ ]:
a.ndim

2

#### 1.3 「行列のデータ型を確認してください。」

In [ ]:
type(a)

numpy.ndarray

#### 1.4 「行列の配列要素を確認してください。」

In [ ]:
a.dtype

dtype('int64')

### 2. 配列について学習します。（4問）

#### 2.1 「8つの「0」が入る配列を作成してください。」

In [ ]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

#### 2.2 「8つの「0」が入る配列を作成し、5番目の値を「1」に変えてください。」

In [ ]:
b = np.zeros(8)
b[4]=1
b

array([0., 0., 0., 0., 1., 0., 0., 0.])

#### 2.3 「10～49までの数字が昇順で入った配列を作成してください。」

In [ ]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 2.4 「0～39までの数字が降順で入った配列を作成してください。」

In [ ]:
np.arange(40)[::-1]

array([39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23,
       22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,
        5,  4,  3,  2,  1,  0])

### 3. スライスについて学習します。（5問）

#### 3.1 「0~9までの数字が入った配列を作成してください。」

In [ ]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 3.2 「スライス（:）を使用して、3.1で作成した配列から下記の配列を取り出して下さい。」

In [ ]:
data[4:8]

array([4, 5, 6, 7])

#### 3.3 「スライス（:）を使用して、3.1で作成した配列から「マイナス」を使用して下記の配列を取り出して下さい。」

In [ ]:
data[-7:-2]

array([3, 4, 5, 6, 7])

#### 3.4 「スライス（:）を使用して、3.1で作成した配列から「マイナス」を使用して下記の配列を取り出して下さい。」

In [ ]:
data[-10:][::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

#### 3.5 「スライス（:）を使用して、3.1で作成した配列から下記の配列を取り出して下さい。」

In [ ]:
data[2:7:2]

array([2, 4, 6])

### 4. 行列について学習します（基礎）（6問）

#### 4.1 「0～8までの数字が昇順で入った配列を作成し、3×3の行列を作成してください。」

In [ ]:
d = np.arange(9)
np.reshape(d,(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 4.2 「任意の「0」が入っている配列を作成し、「0」以外が入っているインデックスを取得してください。」

In [ ]:
e = np.array([1,4,0,5])
np.nonzero(e)

(array([0, 1, 3]),)

#### 4.3 「3×3の正方行列を作成してください。」

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 4.4 「3×3×3のランダム値を持つ行列を作成してください。」

In [ ]:
np.random.random((3,3,3))

array([[[0.65964236, 0.15310254, 0.30429591],
        [0.33635283, 0.11708306, 0.62089575],
        [0.05081019, 0.51583172, 0.98943859]],

       [[0.64271525, 0.3478136 , 0.53508122],
        [0.51377877, 0.90594554, 0.73848212],
        [0.02340854, 0.35976055, 0.01275343]],

       [[0.74217278, 0.18773185, 0.24144693],
        [0.96059587, 0.1139331 , 0.78340893],
        [0.60242666, 0.73185972, 0.67592006]]])

#### 4.5 「10×10のランダム値を持つ行列を作成し、最小値と最大値を出力してください。」

In [ ]:
np.random.random((10,10))

array([[0.20073936, 0.06505838, 0.15546972, 0.24079512, 0.95845223,
        0.79002396, 0.73886383, 0.70109653, 0.10917448, 0.359305  ],
       [0.06773056, 0.05078287, 0.64071397, 0.79107982, 0.30798927,
        0.32049477, 0.64532669, 0.64458065, 0.31053233, 0.48980124],
       [0.71662372, 0.07975221, 0.91091059, 0.52466419, 0.29046871,
        0.82582983, 0.09867132, 0.1639691 , 0.4477838 , 0.38929367],
       [0.84392374, 0.8954799 , 0.57904045, 0.18269636, 0.02475198,
        0.28122603, 0.4587378 , 0.35320764, 0.05128214, 0.31173408],
       [0.59739521, 0.12994798, 0.08189138, 0.89014283, 0.63011238,
        0.01056694, 0.54085334, 0.12236881, 0.5751481 , 0.07531101],
       [0.43605368, 0.02241909, 0.59935937, 0.23245855, 0.89953868,
        0.46828105, 0.97722142, 0.78979129, 0.10221664, 0.45101239],
       [0.94043743, 0.0537405 , 0.37718788, 0.01221061, 0.22125103,
        0.88227834, 0.72548326, 0.37529321, 0.19547257, 0.6041432 ],
       [0.42182093, 0.05216269, 0.2318318

#### 4.6 「10×10のランダム値を持つ行列を作成し、平均値を出力してください。」

### 5. 行列について学習します（応用）（7問）

#### 5.1 「10×10の大きさの、外側だけ値が「1」、内側が全て値が「0」の行列を作成してください。」

#### 5.2 「10×10の大きさの、外側だけ値が「0」、内側が全て値が「1」の行列を作成してください。」

#### 5.3「下記のような4×4の対角行列を作成してください。」

#### 5.4 「下記のような8×8の行列を作成してください。」

#### 5.5「3×5×2の行列を考えた時に、10番目の要素のインデックスを出力してください。」

#### 5.6「5×5のランダム値を持つ行列を作成し、行列内の最大値が1、最小値が0になるように正規化してください。」

#### 5.7「5×3の値が全て1の行列と3×2の値が全て1の行列の掛け算を行ってください。」

### 6. numpyでよく使用する機能について学習します。（14問）

#### 6.1「0～10までの数字を昇順に並べた配列を作成し、4～8までの数字をマイナスに変えて出力してください。」

#### 6.2「ランダムな整数値を10個もつ配列を2つ作成し、その2つの配列の共通の値を出力してください。」

#### 6.3「虚数を出力してください。」

#### 6.4「今日の日付と明後日の日付を出力してください。」

#### 6.5「2019年11月の日付を配列として出力してください。」

#### 6.6「ランダムの値を10個持つ配列を作成し、異なる3パターンで整数として出力してください。」

#### 6.7「下記のような行列を作成してください。」

#### 6.8「「0」と「1」は含めず、「0」～「1」の間を10分割した配列を作成してください。」

#### 6.9「10のランダム値を持つ配列を作成し、値を昇順にして出力してください。」

#### 6.10「10のランダム値を持つ配列を作成し、MAX値に「0」を置き換えて出力してください。」

#### 6.11「下記のような値が軸単位で昇順になっている行列を作成してください。」

#### 6.12「3×3の値が昇順になっている行列を作成し、インデックスと値を出力してください。」

#### 6.13「10×10の「0」行列を作成し、ランダムで20個「1」に変更してください。」

#### 6.14「100の整数のランダム要素を持つ配列を作成し、その頻度を出力してください。」

In [ ]:
g = np.random.randint(0,15,100)
np.bincount(g)

array([ 3,  9,  6,  6,  3,  6,  5,  3,  7,  8,  9,  8, 11,  4, 12])